[package]
name = "deform_grid"
version = "0.1.0"
authors = ["Sven Nilsen <bvssvni@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston2d-graphics = "0.31.0"
